### ISSUE TITLE
As a developer I want sample data for the database

### ISSUE THREAD

**Issue by alexvision** [MasticatingMarsupial/Chew#3]

**Comment by mikejune** [comment]
This should be returned in the following format: 

{ results: [
  {
    id: 1
    name: Hotdog
    rating: 3
    numRatings: 134
    restaurant: Jim's Dogs
  },
  {
    id: 425
    name:  Dirty Dog
    rating: 4
    numRatings: 25
    restaurant: Hotdog Stand
  }
]}

**Comment by alexvision** [comment]
Updated Mock data: 
[
  {
    id: 1,
    name: "Hotdog",
    rating: 3,
    numRatings: 134,
    restaurant: "Jim's Dogs",
    image: ["http://www.jamesaltucher.com/wp-content/uploads/2013/03/HOT-DOG.jpg", "http://www.seriouseats.com/images/20081209-hot-dog.jpg"]
  },
  {
    id: 425,
    name:  "Dirty Dog",
    rating: 4,
    numRatings: 25,
    restaurant: "Hotdog Stand",
    image: ["http://www.seriouseats.com/images/20081209-hot-dog.jpg", "http://www.seriouseats.com/images/20081209-hot-dog.jpg"]
  },
  {
    id: 422,
    name:  "Breakfast Dog",
    rating: 5,
    numRatings: 245,
    restaurant: "Hotdog Stand",
    image: ["http://www.apinchofginger.com/uploads/6/0/3/9/6039210/2338231_orig.jpg", "http://www.seriouseats.com/images/20081209-hot-dog.jpg"]
  }
]
